[versions]
app-versionName = "1.3.1"
app-versionCode = "7"
kotlin = "2.0.0"
agp = "8.7.0-alpha02"
compileSdk = "34"
targetSdk = "34"
minSdk = "27"
compose = "1.6.8"
compose-material3 = "1.2.1"
lifecycle = "2.8.4"
activity = "1.9.1"
preference = "1.2.1"
xposed-api = "82"

[libraries]
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
preference = { module = "androidx.preference:preference-ktx", version.ref = "preference" }
xposed-api = { module = "de.robv.android.xposed:api", version.ref = "xposed-api" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
